return {
    log      = require("apioak.pdk.log"),
    ctx      = require("apioak.pdk.ctx"),
    json     = require("apioak.pdk.json"),
    time     = require("apioak.pdk.time"),
    shared   = require("apioak.pdk.shared"),
    table    = require("apioak.pdk.table"),
    string   = require("apioak.pdk.string"),
    request  = require("apioak.pdk.request"),
    response = require("apioak.pdk.response"),
    schema   = require("apioak.pdk.schema"),
    plugin   = require("apioak.pdk.plugin"),
    admin    = require("apioak.pdk.admin"),
    pool     = require("apioak.pdk.tablepool"),
    const    = require("apioak.pdk.const"),
    database = require("apioak.pdk.database"),
}
