local _M = {}

_M.LOCAL_IP            = "127.0.0.1"

_M.LOCAL_HOST          = "localhost"

_M.BALANCER_CHASH      = "CHASH"

_M.BALANCER_ROUNDROBIN = "ROUNDROBIN"

_M.ENVIRONMENT_PROD    = "PROD"

_M.ENVIRONMENT_BETA    = "BETA"

_M.ENVIRONMENT_TEST    = "TEST"

_M.REQUEST_API_ENV_KEY       = "APIOAK-API-ENV"

_M.REQUEST_ADMIN_TOKEN_KEY   = "APIOAK-ADMIN-TOKEN"

_M.RESPONSE_MOCK_REQUEST_KEY = "APIOAK-MOCK-REQUEST"

_M.REQUEST_PARAM_POS_QUERY  = "QUERY"

_M.REQUEST_PARAM_POS_PATH   = "PATH"

_M.REQUEST_PARAM_POS_HEADER = "HEADER"

_M.CONTENT_TYPE        = "Content-Type"

_M.CONTENT_TYPE_JSON   = "application/json"

_M.CONTENT_TYPE_HTML   = "text/html"

_M.CONTENT_TYPE_XML    = "text/xml"

return _M
